### ISSUE TITLE
Juniper Documentation

### ISSUE THREAD

**Issue by robertlynch3** [farsonic/dynamic-address#3]
I know this is a super old project, but is it possible to send me the Juniper Documentation you used? 

I am trying to implement this but hitting a few snags. Mainly how the md5 is calculated. I'd love to be able to see what the SRX expects. 

Thank you!!!

**Comment by farsonic** [comment]
Sorry, this was based on internal documentation which I no longer have access to....no longer working at Juniper Networks. The code should provide some hints....I'd need to dig in the back of my brain for this one. You can also look at using OneConfig as they have a functional and supported implementation for providing SRX with dynamic address objects.

**Comment by robertlynch3** [comment]
Really appreciate the reply. I’ll look into OneConfig! I actually combed through your files and was able to figure out what the SRX expects to see. I was not able to figure out how to get URLs in the dynamic addresses though. I also was trying to see if you had anything for dynamic policies.
